name: Build and Deploy to Vercel

permissions:
  contents: write

on:
  push:
    branches:
      - main  # 当 fork 仓库的 main 分支有更新时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build_and_deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Vercel CLI
      - name: Install Vercel CLI
        run: |
          npm install -g vercel  # 安装 Vercel CLI

      # Step 3: Deploy to Vercel (自动确认部署)
      - name: Deploy to Vercel
        run: |
          vercel --prod --yes  # 自动部署并跳过确认
