name: Build and Deploy to Vercel

permissions:
  contents: write

on:
  push:
    branches:
      - main  # 当 fork 仓库的 main 分支有更新时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build_and_deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy to Vercel (自动部署，无需 API Token)
      - name: Deploy to Vercel
        run: |
          vercel --prod  # 部署到 Vercel
