name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main  # 或者 master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # 设置 Node.js 的版本（根据需要调整）

      - name: Install pnpm
        uses: pnpm/action-setup@v4  # 安装 pnpm
        with:
          version: '6'  # 设置 pnpm 的版本（根据需要调整）

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          npm run build

      - name: Deploy to Vercel (GitHub Actions Integration)
        run: |
          vercel --prod
