name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main  # 或者 master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          npm run build

      - name: Deploy to Vercel (GitHub Actions Integration)
        run: |
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # 如果你有 Vercel Token 也可以设置它，但现在不需要
